typedef enum {
   PHX_PARAM_MASK                = (int) 0xffffff00,
   PHX_INVALID_PARAM             = 0,
   PHX_CACHE_FLUSH               = 1,
   PHX_FORCE_REWRITE             = 2,

   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_CONTINUOUS,                     1 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_NUM_BUFFERS,                    2 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_SKIP,                           3 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_FGTRIG_SRC,                         4 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_FGTRIG_MODE,                        5 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_FIELD_MODE,                     6 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_XSUB,                           7 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_YSUB,                           8 ),

   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_ACTIVE_XLENGTH,                10 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_ACTIVE_YLENGTH,                11 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_ACTIVE_XOFFSET,                12 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_ACTIVE_YOFFSET,                13 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_CLOCK_POLARITY,                14 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_FORMAT,                        15 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_NUM_TAPS,                      16 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_SRC_DEPTH,                     17 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_SRC_COL,                       18 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_HTAP_DIR,                      19 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_HTAP_TYPE,                     20 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_HTAP_NUM,                      21 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_VTAP_DIR,                      22 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_VTAP_TYPE,                     23 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_VTAP_NUM,                      24 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_TYPE,                          25 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_XBINNING,                      26 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_YBINNING,                      27 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COMMS_DATA,                        28 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COMMS_FLOW,                        29 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COMMS_INCOMING,                    30 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COMMS_OUTGOING,                    31 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COMMS_PARITY,                      32 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COMMS_SPEED,                       33 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COMMS_STANDARD,                    34 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COMMS_STOP,                        35 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_DATASRC,                           36 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_DATASTREAM_VALID,                  37 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_BUS_FORMAT,                        38 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_DST_PTR_TYPE,                      39 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_DST_PTRS_VIRT,                     40 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_DUMMY_PARAM,                       41 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ERROR_FIRST_ERRNUM,                42 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ERROR_FIRST_ERRSTRING,             43 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ERROR_HANDLER,                     44 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ERROR_LAST_ERRNUM,                 45 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ERROR_LAST_ERRSTRING,              46 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COUNTE1_VALUE_NOW,                 47 ),

   _PHX_ENUM( PHX_SETANDGET, PHX_NUM_BOARDS,                        61 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_CCIO_A,                         62 ),  /* Absolute */
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_CCIO_A_OUT,                     63 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_CCIO_B,                         64 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_CCIO_B_OUT,                     65 ),

   _PHX_ENUM( PHX_SETANDGET, PHX_IO_OPTO_SET,                       68 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_OPTO_CLR,                       69 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_OPTO,                           70 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_TTL_A,                          71 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_TTL_A_OUT,                      72 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_TTL_B,                          73 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_TTL_B_OUT,                      74 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_TIMEOUT_CAPTURE,                   75 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_TIMEOUT_DMA,                       76 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_TIMEOUT_TRIGGER,                   77 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_INTRPT_SET,                        78 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_INTRPT_CLR,                        79 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_REV_HW,                            80 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_REV_HW_MAJOR,                      81 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_REV_HW_MINOR,                      82 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_REV_SW,                            83 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_REV_SW_MAJOR,                      84 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_REV_SW_MINOR,                      85 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_REV_SW_SUBMINOR,                   86 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ROI_DST_XOFFSET,                   87 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ROI_DST_YOFFSET,                   88 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ROI_SRC_XOFFSET,                   89 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ROI_SRC_YOFFSET,                   90 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ROI_XLENGTH,                       91 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ROI_YLENGTH,                       92 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_BUF_DST_XLENGTH,                   93 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_BUF_DST_YLENGTH,                   94 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_STATUS,                        95 ),

   _PHX_ENUM( PHX_SETANDGET, PHX_BOARD_PROPERTIES,                 102 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ROI_XLENGTH_SCALED,               103 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ROI_YLENGTH_SCALED,               104 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_BUF_SET,                          105 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_BUF_SET_COLOUR,                   106 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_LUT_COUNT,                        107 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_LUT_INFO,                         108 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_REV_HW_SUBMINOR,                  109 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_LUT_CORRECT,                      110 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_LINETRIG_SRC,                     111 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_LINETRIG_TIMER_CTRL,              112 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_TIMERA1_PERIOD,                   113 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAMTRIG_SRC,                      114 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_EXP_CTRLIO_1,                     115 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_TIMERM1_WIDTH,                    116 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_EXP_CTRLIO_2,                     117 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_TIMERM2_WIDTH,                    118 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_EXP_LINESTART,                    119 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_FGTRIG_DELAY_MODE,                120 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_TIMERD1_VALUE,                    121 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_EVENTCOUNT_SRC,                   122 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_EVENTGATE_SRC,                    123 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_HTAP_ORDER,                   124 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_VTAP_ORDER,                   125 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_EVENT_CONTEXT,                    126 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_DATA_VALID,                   127 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COUNT_BUFFER_READY,               128 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COUNT_BUFFER_READY_NOW,           129 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_BIT_SHIFT,                        130 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_CCIO,                          131 ),  /* Relative */
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_CCIO_OUT,                      132 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_TTL,                           133 ),  /* Relative */
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_TTL_OUT,                       134 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_OPTO_A,                        135 ),  /* Absolute */
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_OPTO_B,                        136 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_TIMER_A1_PERIOD,               137 ),  /* Absolute */
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_TIMER_A2_PERIOD,               138 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_TIMER_B1_PERIOD,               139 ),  /* Absolute */
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_TIMER_B2_PERIOD,               140 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_OPTO_OUT,                      141 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_OPTO_A_OUT,                    142 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_IO_OPTO_B_OUT,                    143 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_FGTRIG_ALIGN,                     144 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_DST_ENDIAN,                       145 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_CHAIN,                        146 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_BLOCKING,                     147 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_DST_PTRS_PHYS32,                  148 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_BOARD_INFO,                       149 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_DATARATE_TEST,                    150 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_CLOCK_MAX,                    151 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COUNTE1_VALUE_DB,                 152 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CHAN_SYNC_MODE,                   153 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_BUFFER_START,                 154 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_LUT_BYPASS,                       155 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_COMMS_PORT_NAME,                  156 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CVB_PARAM,                        157 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_USR_FORMAT,                       158 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_AUTO_RESTART,                 159 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_HSCALE,                       160 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_MERGE_CHAN,                       161 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_MERGE_INTRPT_SET,                 162 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_MERGE_INTRPT_CLR,                 163 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CLSER_INDEX,                      164 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_FIFO_BUFFER_COUNT,                165 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_REV_FW_FLASH,                     166 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_REV_FW_LIB,                       167 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_PCIE_INFO,                        168 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_TAP_MODE,                         169 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_ACQ_IMAGES_PER_BUFFER,            170 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_DST_PTRS_PHYS64,                  171 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_CAM_VTAP_INTERLEAVE_NUM,          172 ),
   _PHX_ENUM( PHX_SETANDGET, PHX_REV_DRV,                          173 ),


   PHX_IO_CCOUT_A                = PHX_IO_CCIO_A,
   PHX_IO_CCOUT_B                = PHX_IO_CCIO_B,
   PHX_IO_CCOUT                  = PHX_IO_CCIO,
   PHX_MASK_CCIO                 = (int) 0x00000003,
   PHX_MASK_CCOUT                = (int) 0x0000000f,
   PHX_MASK_OPTO                 = (int) 0x0000000f,


   _PHX_ENUM( PHX_PRE_OPEN, PHX_CONFIG_FILE,                         1 ),
   _PHX_ENUM( PHX_PRE_OPEN, PHX_BOARD_VARIANT,                       2 ),
   _PHX_ENUM( PHX_PRE_OPEN, PHX_BOARD_NUMBER,                        3 ),
   _PHX_ENUM( PHX_PRE_OPEN, PHX_CHANNEL_NUMBER,                      4 ),
   _PHX_ENUM( PHX_PRE_OPEN, PHX_CONFIG_MODE,                         5 ),
   _PHX_ENUM( PHX_PRE_OPEN, PHX_CONFIG_FLUSH,                        6 ),
   _PHX_ENUM( PHX_PRE_OPEN, PHX_BOARD_BUS_ADDRESS,                   7 ),


   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_INFO,                       1 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_BITRATE,                    2 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_POCXP,                      3 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_DISCOVERY,                  4 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_LINKTEST_UPLINK_OK,         5 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_LINKTEST_UPLINK_ERR,        6 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_LINKTEST_DOWNLINK_OK,       7 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_LINKTEST_DOWNLINK_ERR,      8 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_ERRCOUNT_LINK_LOSS,         9 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_ERRCOUNT_8B10B,            10 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_ERRCOUNT_CRC_STREAM,       11 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_ERRCOUNT_CRC_CTRL,         12 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_ERRCOUNT_CRC_EVENT,        13 ),
   /* Note 14 is not used to maintain backward compatibility */

   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMERA_POWER,                  15 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_BITRATE_MODE,              16 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_POCXP_MODE,                17 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_DISCOVERY_MODE,            18 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_UPLINK_TEST,               19 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_DOWNLINK_TEST,             20 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_422IN_CHX,                  21 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_422IN_CH1,                  22 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_422IN_CH2,                  23 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_422IN_CH3,                  24 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_422IN_CH4,                  25 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_OPTOIN_CHX,                 26 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_OPTOIN_CH1,                 27 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_OPTOIN_CH2,                 28 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_OPTOIN_CH3,                 29 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_OPTOIN_CH4,                 30 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_TTLIN_CHX,                  31 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_TTLIN_CH1,                  32 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_TTLIN_CH2,                  33 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_TTLIN_CH3,                  34 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_TTLIN_CH4,                  35 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_422OUT_CHX,                 36 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_422OUT_CH1,                 37 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_422OUT_CH2,                 38 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_422OUT_CH3,                 39 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_422OUT_CH4,                 40 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_OPTOOUT_CHX,                41 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_OPTOOUT_CH1,                42 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_OPTOOUT_CH2,                43 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_OPTOOUT_CH3,                44 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_OPTOOUT_CH4,                45 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_TTLOUT_CHX,                 46 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_TTLOUT_CH1,                 47 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_TTLOUT_CH2,                 48 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_TTLOUT_CH3,                 49 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_TTLOUT_CH4,                 50 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_CCOUT_CHX,                  51 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_CCOUT_CH1,                  52 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_CCOUT_CH2,                  53 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_CCOUT_CH3,                  54 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_CCOUT_CH4,                  55 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMTRIG_ENCODER_MODE,          56 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMTRIG_ENCODER_SRC,           57 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMTRIG_MULTIPLIER,            58 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMTRIG_DIVIDER,               59 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMTRIG_CXPTRIG_SRC,           60 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMTRIG_CXPTRIG_MODE,          61 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMTRIG_DELAY_MODE,            62 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERD2_VALUE,                 63 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_FW_NUM_DESIGNS,                64 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_FW_DESIGN_LIB,                 65 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_FW_DESIGN_PROG,                66 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_FW_DESIGN_FLASH,               67 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_STR_DESIGN_LIB,                68 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_STR_DESIGN_FLASH,              69 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_FGTRIG_FILTER_NS,              70 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMTRIG_FILTER_NS,             71 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMTRIG_ENCODER_FILTER_NS,     72 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERA1_PERIOD_NS,             73 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERD1FG_VALUE_NS,            74 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERM1_WIDTH_NS,              75 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERM2_WIDTH_NS,              76 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERD2_VALUE_NS,              77 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_FPGA_CORE_TEMP,                78 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMTRIG_DELAY_MODE_D1CAM,      79 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CAMTRIG_DELAY_MODE_D2CAM,      80 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERD1FG_COUNT,               81 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERA1_MODE,                  82 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERA1_PULSE_COUNT,           83 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERA1_SWTRIG,                84 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERD1CAM_VALUE_NS,           85 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERD2CAM_VALUE_NS,           86 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IMAGE_TIMESTAMP_MODE,          87 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_DST_ALIGNMENT,                 88 ),

#if 0
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_POCXP_TRIP_RESET,          89 ),
#endif

   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_HEADER,                    90 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IRIG_TRIG_COUNT,               91 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VOUT_CHX,                 92 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VOUT_CH1,                 93 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VOUT_CH2,                 94 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VOUT_CH3,                 95 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VOUT_CH4,                 96 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VIN_CHX,                  97 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VIN_CH1,                  98 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VIN_CH2,                  99 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VIN_CH3,                 100 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VIN_CH4,                 101 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VIN_CH5,                 102 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VIN_CH6,                 103 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VIN_CH7,                 104 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_IO_24VIN_CH8,                 105 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_SERIAL_NUMBER,                106 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_RETAIN_CXP_DISCOVERY,         107 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CL_LVAL_FILTER,               108 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_ERRCOUNT_DUP_FIXED,       109 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_ERRCOUNT_DUP_NFIXED,      110 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_ERRCOUNT_FEC_FIXED,       111 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CXP_ERRCOUNT_FEC_NFIXED,      112 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_ACQ_BUFFER_MEMSET_MODE,       113 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_ACQ_BUFFER_MEMSET_VALUE,      114 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_CL_POCL_MODE,                 115 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERA1_TRIG_SRC,             116 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_TIMERA1_TRIG_FILTER_NS,       117 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_MEZZANINE_GUID,               118 ),
   _PHX_ENUM( PHX_FBD_SETANDGET, PHX_USER_ID,                      119 ),


   PHX_CL_INFO                   = PHX_CXP_INFO,


#if !defined _PHX_NO_BACKWARDS_COMPATIBILITY_
   /* Retained for backwards compatibility with previous software releases.
    * Do not use for new applications
    */
   PHX_ACQ_NUM_IMAGES            = PHX_ACQ_NUM_BUFFERS,        /*   2 << 8 */
   PHX_ACQTRIG_SRC               = PHX_FGTRIG_SRC,             /*   4 << 8 */
   PHX_ACQTRIG_TYPE              = PHX_FGTRIG_MODE,            /*   5 << 8 */
   PHX_ACQ_TYPE                  = PHX_ACQ_FIELD_MODE,         /*   6 << 8 */
   PHX_CAM_SRC_BANDS             = PHX_CAM_SRC_COL,            /*  18 << 8 */
   PHX_CAPTURE_FORMAT            = PHX_BUS_FORMAT,             /*  38 << 8 */
   PHX_DST_FORMAT                = PHX_BUS_FORMAT,
   PHX_DST_PTRS                  = PHX_DST_PTRS_VIRT,          /*  40 << 8 */
   PHX_EVENTCOUNT                = PHX_COUNTE1_VALUE_NOW,      /*  47 << 8 */
   PHX_EVENT_COUNT               = PHX_COUNTE1_VALUE_NOW,
   PHX_IO_LVDS_A                 = PHX_IO_CCIO_A,              /*  62 << 8 */
   PHX_IO_LVDS_A_OUT             = PHX_IO_CCIO_A_OUT,          /*  63 << 8 */
   PHX_IO_LVDS_B                 = PHX_IO_CCIO_B,              /*  64 << 8 */
   PHX_IO_LVDS_B_OUT             = PHX_IO_CCIO_B_OUT,          /*  65 << 8 */
   PHX_LINETRIG_TIMER_PERIOD     = PHX_TIMERA1_PERIOD,         /* 113 << 8 */
   PHX_EXPTRIG_SRC               = PHX_CAMTRIG_SRC,            /* 114 << 8 */
   PHX_EXP_SRC                   = PHX_CAMTRIG_SRC,
   PHX_IO_TIMER_1_PERIOD         = PHX_TIMERM1_WIDTH,          /* 116 << 8 */
   PHX_EXP_CTRLIO_1_DELAY        = PHX_TIMERM1_WIDTH,
   PHX_IO_TIMER_2_PERIOD         = PHX_TIMERM2_WIDTH,          /* 118 << 8 */
   PHX_EXP_CTRLIO_2_DELAY        = PHX_TIMERM2_WIDTH,
   PHX_ACQTRIG_DELAY_TYPE        = PHX_FGTRIG_DELAY_MODE,      /* 120 << 8 */
   PHX_ACQTRIG_DELAY             = PHX_TIMERD1_VALUE,          /* 121 << 8 */
   PHX_EVENTCOUNT_TYPE           = PHX_EVENTCOUNT_SRC,         /* 122 << 8 */
   PHX_EVENTGATE_TYPE            = PHX_EVENTGATE_SRC,          /* 123 << 8 */
   PHX_BUFFER_READY_COUNT        = PHX_COUNT_BUFFER_READY,     /* 128 << 8 */
   PHX_BUFFER_READY_COUNTER      = PHX_COUNT_BUFFER_READY_NOW, /* 129 << 8 */
   PHX_LUT_SHIFT                 = PHX_BIT_SHIFT,              /* 130 << 8 */
   PHX_IO_422_OUT                = PHX_IO_CCIO_OUT,            /* 132 << 8 */
   PHX_ACQTRIG_ALIGN             = PHX_FGTRIG_ALIGN,           /* 144 << 8 */
   PHX_EVENTCOUNT_AT_GATE        = PHX_COUNTE1_VALUE_DB,       /* 152 << 8 */
   PHX_USER_FORMAT               = PHX_USR_FORMAT,             /* 158 << 8 */
   PHX_REV_FLASH                 = PHX_REV_FW_FLASH,           /* 166 << 8 */
   PHX_TIMERD1_VALUE_NS          = PHX_TIMERD1FG_VALUE_NS,     /*  74 << 8 */
   PHX_STATUS                    = PHX_ACQ_STATUS,
   PHX_DST_PTRS_PHYS             = PHX_DST_PTRS_PHYS32
#endif
} etParam;